services:
  mongodb:
    image: mongo:8.3.3
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_root_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
    volumes:
      - mongo_data:/data/db
    secrets:
      - mongo_root_user
      - mongo_root_password
    networks:
      - db_network

  postgis:
    image: postgis/postgis:17-master
    container_name: postgis
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: gis
    volumes:
      - postgis_data:/var/lib/postgresql/data
    secrets:
      - postgres_user
      - postgres_password
    networks:
      - db_network

secrets:
  mongo_root_user:
    file: ./secrets/mongo_root_user.txt
  mongo_root_password:
    file: ./secrets/mongo_root_password.txt
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt

volumes:
  mongo_data:
  postgis_data:

networks:
  db_network:
    driver: bridge